config/routes.rb
class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end


Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :graphs, only: [:show,:index]

  resources :patients do
    collection do
      post :import
    end
  end

  resources :kansatus do
    collection do
      get :search
      post :import
    end
  end
  
  resources :tentous do
    collection do
      get :search
      post :import
    end
  end

  resources :saiketus do
    collection do
      get :search
      post :import
    end
  end
  resources :sensors

  resources :kekkas
  resources :plans

  resources :pdetails do
    collection do
      post :import
    end
  end

  resources :nreports

end

app/models/form/pdetail.rb
class Form::Pdetail < Pdetail
  REGISTRABLE_ATTRIBUTES = %i(register plan_id kubun naiyo hyouka hyokad)
  attr_accessor :register
end

app/models/pdetail.rb
class Pdetail < ApplicationRecord
  belongs_to :plan
validates :naiyo,    length: { maximum: 200 }
enum kubun: {ＯＰ:0, ＴＰ:1, ＥＰ:2}
enum hyouka: {続行:0, 解決:1, 中止:2}

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      pdetail = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      pdetail.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      pdetail.save!
    end
  end 

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["kubun","naiyo","hyouka","hyokad","plan_id"]
  end

end

app/controllers/pdetails_controller.rb
class PdetailsController < ApplicationController
  before_action :require_user_logged_in
  def index
    @plans = Plan.all.includes(:pdetails)
    @pdetails = Pdetail.all

    def import
      # fileはtmpに自動で一時保存される
      Pdetail.import(params[:file])
      redirect_to pdetails_url, notice: "追加しました。"
    end
  end

  def show
    @plan = Plan.find(params[:id])
    @pdetails = @plan.pdetails
  end

  def new
    @pdetail = Pdetail.new
  end

  def create
    @pdetail = Pdetail.new(pdetail_params)

    if @pdetail.save
      flash[:success] = '正常に投稿されました'
      redirect_to action: 'index'
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end


  def edit
    @pdetail = Pdetail.find(params[:id])
  end

  def update
    @pdetail = Pdetail.find(params[:id])

    if @pdetail.update(pdetail_params)
      flash[:success] = '正常に更新されました'
      redirect_to action: 'index'
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @pdetail = Pdetail.find(params[:id])
    @pdetail.destroy

    flash[:success] = '正常に削除されました'
    redirect_to pdetails_url

  end

  private

  def pdetail_params
    params.require(:pdetail).permit(:plan_id,
:kubun,:naiyo,:hyouka,:hyokad
    )
  end

end

app/views/pdetails/_form.html.erb
<%= form_for(pdetail) do |f| %>
  <div class="row">
    <div class="col-sm-6">
<form class="form-inline">

  <div class="form-group">
    <%= f.label :plan_id, 'planＩＤ' %>
    <%= f.text_field :plan_id, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :kubun, '区分' %>
    <%= f.select :kubun, Pdetail.kubuns.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="form-group">
    <%= f.label :naiyo, '内容' %>
    <%= f.text_field :naiyo, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :hyouka, '評価' %>
    <%= f.select :hyouka, Pdetail.hyoukas.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="form-group">
    <%= f.label :hyokad, '評価日' %>
    <%= f.date_select(:hyokad,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>

  
  <button type="submit" class="btn btn-primary">投稿</button>
</form>

</div>
</div>
<% end %>

app/views/pdetails/edit.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>id: <%= @pdetail.id %> の編集ページ</h1>

<%= render 'form', pdetail: @pdetail %>

<%= link_to '一覧に戻る', pdetails_path %>
<%= link_to '削除', @pdetail, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/pdetails/index.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>

<div class="col-sm-10">
<% @plans.each do |plan| %>
<h2>
<a href="../pdetails/<%= plan.id %>">show</a>
</h2>

   
<table class="table table-striped table-bordered table-condensed table-hover" style="table-layout:fixed;width:100%;">
  <tr>
   <th style="width:5%" class="text-center">plan_ID</th>
   <th style="width:5%" class="text-center">id</th>
   <th style="width:7%" class="text-center">区分</th>
   <th style="width:60%" class="text-center">内容</th>
   <th style="width:7%" class="text-center">評価</th>
   <th style="width:15%" class="text-center">評価日</th> 
  </tr>
<% plan.pdetails.each do |pdetail| %>
  <tr>
   <th style="width:5%" class="text-center"><%= pdetail.plan_id %></th>
   <td style="width:5%" class="text-center"><%= link_to pdetail.id, edit_pdetail_path(pdetail) %></td>
   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.kubun %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.naiyo %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.hyouka %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.hyokad %></td>
  </tr>

  <% end %>
</table>

<% end %>


<%= form_tag import_pdetails_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>
<%= link_to '新規投稿', new_pdetail_path %>
</div>

<div class="row col-sm-2">
<%= render 'layouts/sidebar' %>
</div>

app/views/pdetails/new.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>新規作成ページ</h1>

<%= render 'form', pdetail: @pdetail %>

<%= link_to '一覧に戻る', pdetails_path %>

app/views/pdetails/show.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>

<div class="col-sm-10">
<div class="col-sm-10">
<h2>#<%= @plan.plno %>&emsp;<%= @plan.name %></h2>
</div>
<div class="col-sm-2">
<%= link_to '看護計画一覧', plan_path(1), class: 'btn btn-primary btn-lg active' %>
</div>

<table class="table table-striped table-bordered table-condensed table-hover" style="table-layout:fixed;width:100%;">
  <tr class="info">
   <th style="width:13%" class="text-center">登録日</th>
   <th style="width:13%" class="text-center">評価日</th>
   <th style="width:7%" class="text-center">評価</th>
   <th style="width:13%" class="text-center">次回評価日</th> 
  </tr>
  <tr>
   <td style="word-wrap:break-word;" class="text-left"><%= @plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= @plan.hyokad.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= @plan.hyouka %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= @plan.jikai.strftime('%Y年%m月%d日') %></td>
  </tr>
</table>

<div class="col-sm-6">
<div class="panel panel-info">
  <div class="panel-heading">決定根拠・定義</div>
  <div class="panel-body">
    <%= simple_format @plan.konkyo %>
  </div>
</div>
</div>
<div class="col-sm-6">
<div class="panel panel-info">
  <div class="panel-heading">診断指標</div>
  <div class="panel-body">
    <%= @plan.sihyo_1 %>&emsp;
    <%= @plan.sihyo_2 %>&emsp;
    <%= @plan.sihyo_3 %>
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">関連因子</div>
  <div class="panel-body">
    <%= @plan.kanren_1 %>&emsp;
    <%= @plan.kanren_2 %>&emsp;
    <%= @plan.kanren_3 %>
  </div>
</div>
</div>

<div class="col-sm-12">
  <table class="table table-condensed table-bordered">
  <tr class="info">
   <th class="text-center">患者目標</th>
   <th class="text-center">評価</th>
   <th class="text-center">評価日</th>
  </tr>
  <tr>
    <td><%= @plan.mokuhyo_1 %></td>
    <td><%= truncate(@plan.mhyouka_1, length:3) %></td>
    <td><%= @plan.mhyoud_1 %></td>
  </tr>
<% unless @plan.mokuhyo_2 == '' %>
  <tr>
    <td><%= @plan.mokuhyo_2 %></td>
    <td><%= truncate(@plan.mhyouka_2, length:3) %></td>
    <td><%= @plan.mhyoud_2 %></td>
  </tr>
<% end %>
<% unless @plan.mokuhyo_3 == '' %>
  <tr>
    <td><%= @plan.mokuhyo_3 %></td>
    <td><%= truncate(@plan.mhyouka_3, length:3) %></td>
    <td><%= @plan.mhyoud_3 %></td>
  </tr>
<% end %>
<% unless @plan.mokuhyo_4 == '' %>
  <tr>
    <td><%= @plan.mokuhyo_4 %></td>
    <td><%= truncate(@plan.mhyouka_4, length:3) %></td>
    <td><%= @plan.mhyoud_4 %></td>
  </tr>
<% end %>
<% unless @plan.mokuhyo_5 == '' %>
  <tr>
    <td><%= @plan.mokuhyo_5 %></td>
    <td><%= truncate(@plan.mhyouka_5, length:3) %></td>
    <td><%= @plan.mhyoud_5 %></td>
  </tr>
<% end %>
  </table>
</div>


<table class="table table-striped table-bordered table-condensed table-hover" style="table-layout:fixed;width:100%;">
  <tr class="info">
   <th style="width:7%" class="text-center">区分</th>
   <th style="width:68%" class="text-center">内容</th>
   <th style="width:7%" class="text-center">評価</th>
   <th style="width:13%" class="text-center">評価日</th>
  </tr>
<% @pdetails.each do |pdetail| %>
  <tr>
<% if pdetail.kubun == 'ＯＰ' %>
   <td class="danger"><%= pdetail.kubun %></td> 
<% elsif pdetail.kubun == 'ＴＰ' %>
   <td class="warning"><%= pdetail.kubun %></td> 
<% else %>
   <td class="success"><%= pdetail.kubun %></td> 
<% end %>

   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.naiyo %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.hyouka %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= pdetail.hyokad %></td> 
  </tr>
<% end %>
</table>

<%= link_to '一覧に戻る', pdetails_path %>
</div>

<div class="row col-sm-2">
<%= render 'layouts/sidebar' %>
</div>