config/routes.rb
class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end


Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :graphs, only: [:show,:index]

  resources :patients do
    collection do
      post :import
    end
  end

  resources :kansatus do
    collection do
      get :search
      post :import
    end
  end
  
  resources :tentous do
    collection do
      get :search
      post :import
    end
  end

  resources :saiketus do
    collection do
      get :search
      post :import
    end
  end
  resources :sensors

  resources :kekkas
  resources :plans

  resources :pdetails do
    collection do
      post :import
    end
  end

  resources :nreports

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :section, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :destroy]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all.page(params[:page]).per(10)
    @count_users = User.count
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = '正常に削除されました'
    redirect_to users_url
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :section, :password, :password_confirmation)
  end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end



end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/create.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :section %>
      <%= f.text_field :section, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
<br>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

app/views/users/index.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>アンケート集計</h1>


<button class="btn btn-primary" type="button">
  参加人数 <span class="badge"><%= @count_users %></span>
</button>

  <% if current_user.admin? %>
<div class="row"><div class="col-md-6">
<table class="table table-condensed">
  <tr>
   <th class="text-left">name</th> 
   <th class="text-left">所属</th> 
   <th class="text-left">アンケート</th> 
   <th class="text-left"></th>
  </tr>

  <% @users.each do |user| %>
  <tr>
   <td style="word-wrap:break-word;"><%= link_to user.name, user %></td>
   <td style="word-wrap:break-word;"><%= user.section %></td> 
   <td style="word-wrap:break-word;"><h4><span class="label label-primary">未</span></h4></td> 
   <td style="word-wrap:break-word;">
    <%= link_to '退会', user, method: :delete, data: { confirm: '本当に退会してよろしいですか？' } %>
   </td>

  </tr>

  <% end %>
</table>
<%= paginate @users %>
</div>
  <% end %>

app/views/users/new.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :section, '所属' %>
            <%= f.text_field :section, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
    <%= link_to 'グラフ', graphs_path, class: 'btn btn-success' %>
    <%= link_to '患者', patients_path, class: 'btn btn-success' %>
    <%= link_to '観察', kansatus_path, class: 'btn btn-success' %>
    <%= link_to '転倒', tentous_path, class: 'btn btn-success' %>
    <%= link_to 'sensor', sensors_path, class: 'btn btn-success' %>
    <%= link_to '採血一覧', kekkas_path, class: 'btn btn-success' %>
    <%= link_to '採血抽出', saiketus_path, class: 'btn btn-success' %>
    <%= link_to '看護計画', plans_path, class: 'btn btn-success' %>
    <%= link_to '看護計画詳細', pdetails_path, class: 'btn btn-success' %>

  </div>
  
</div>
<%= render 'layouts/footer' %>