config/routes.rb
class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end


Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :graphs, only: [:show,:index]

  resources :patients do
    collection do
      post :import
    end
  end

  resources :kansatus do
    collection do
      get :search
      post :import
    end
  end
  
  resources :tentous do
    collection do
      get :search
      post :import
    end
  end

  resources :saiketus do
    collection do
      get :search
      post :import
    end
  end
  resources :sensors

  resources :kekkas
  resources :plans

  resources :pdetails do
    collection do
      post :import
    end
  end

  resources :nreports

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :patient
  has_many :pdetails
validates :name,    length: { maximum: 20 }
validates :konkyo,    length: { maximum: 200 }
validates :sihyo_1,    length: { maximum: 100 }
validates :sihyo_2,    length: { maximum: 100 }
validates :sihyo_3,    length: { maximum: 100 }
validates :kanren_1,    length: { maximum: 100 }
validates :kanren_2,    length: { maximum: 100 }
validates :kanren_3,    length: { maximum: 100 }
validates :mokuhyo_1,    length: { maximum: 50 }
validates :mokuhyo_2,    length: { maximum: 50 }
validates :mokuhyo_3,    length: { maximum: 50 }
validates :mokuhyo_4,    length: { maximum: 50 }
validates :mokuhyo_5,    length: { maximum: 50 }

enum hyouka: {続行:0, 解決:1, 中止:2}
enum mhyouka_1: {続行１:0, 解決１:1, 中止１:2}
enum mhyouka_2: {続行２:0, 解決２:1, 中止２:2}
enum mhyouka_3: {続行３:0, 解決３:1, 中止３:2}
enum mhyouka_4: {続行４:0, 解決４:1, 中止４:2}
enum mhyouka_5: {続行５:0, 解決５:1, 中止５:2}


end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :require_user_logged_in
  def index
    @patients = Patient.all.includes(:plans)
    @plans = Plan.all
  end

  def show
    @patient = Patient.find(params[:id])
    @plans = @patient.plans
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)

    if @plan.save
      flash[:success] = '正常に投稿されました'
      redirect_to action: 'index'
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])

    if @plan.update(plan_params)
      flash[:success] = '正常に更新されました'
      redirect_to action: 'index'
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    flash[:success] = '正常に削除されました'
    redirect_to plans_url

  end

  private

  def plan_params
    params.require(:plan).permit(:patient_id,
:name,:touroku,:hyouka,:jikai,:konkyo,:sihyo_1,:sihyo_2,:sihyo_3,
:kanren_1,:kanren_2,:kanren_3,
:mokuhyo_1,:mokuhyo_2,:mokuhyo_3,:mokuhyo_4,:mokuhyo_5,
:mhyouka_1,:mhyouka_2,:mhyouka_3,:mhyouka_4,:mhyouka_5,
:mhyoud_1,:mhyoud_2,:mhyoud_3,:mhyoud_4,:mhyoud_5,:hyokad,:plno
    )
  end

end

app/views/plans/_form.html.erb
<%= form_for(plan) do |f| %>
  <div class="row">
    <div class="col-sm-6">
<form class="form-inline">

    <div class="form-group">
    <%= f.label :patient_id, '患者ＩＤ' %>
    <%= f.text_field :patient_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :plno, '問題番号' %>
    <%= f.text_field :plno, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, '看護問題' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :touroku, '登録日' %>
    <%= f.date_select(:touroku,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>
  <div class="form-group">
    <%= f.label :hyokad, '評価日' %>
    <%= f.date_select(:hyokad,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>

  <div class="field">
    <%= f.label :hyouka, '評価' %>
    <%= f.select :hyouka, Plan.hyoukas.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="form-group">
    <%= f.label :jikai, '次回評価日' %>
    <%= f.date_select(:jikai,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>
  <div class="form-group">
    <%= f.label :konkyo, '診断根拠' %>
    <%= f.text_field :konkyo, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sihyo_1, '診断指標１' %>
    <%= f.text_field :sihyo_1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sihyo_2, '診断指標２' %>
    <%= f.text_field :sihyo_2, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sihyo_3, '診断指標３' %>
    <%= f.text_field :sihyo_3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :kanren_1, '関連指標１' %>
    <%= f.text_field :kanren_1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :kanren_2, '関連指標２' %>
    <%= f.text_field :kanren_2, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :kanren_3, '関連指標３' %>
    <%= f.text_field :kanren_3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mokuhyo_1, '患者目標１' %>
    <%= f.text_field :mokuhyo_1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mokuhyo_2, '患者目標２' %>
    <%= f.text_field :mokuhyo_2, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mokuhyo_3, '患者目標３' %>
    <%= f.text_field :mokuhyo_3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mokuhyo_4, '患者目標４' %>
    <%= f.text_field :mokuhyo_4, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mokuhyo_5, '患者目標５' %>
    <%= f.text_field :mokuhyo_5, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :mhyouka_1, '目標評価１' %>
    <%= f.select :mhyouka_1, Plan.mhyouka_1s.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="field">
    <%= f.label :mhyouka_2, '目標評価２' %>
    <%= f.select :mhyouka_2, Plan.mhyouka_2s.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="field">
    <%= f.label :mhyouka_3, '目標評価３' %>
    <%= f.select :mhyouka_3, Plan.mhyouka_3s.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="field">
    <%= f.label :mhyouka_4, '目標評価４' %>
    <%= f.select :mhyouka_4, Plan.mhyouka_4s.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="field">
    <%= f.label :mhyouka_5, '目標評価５' %>
    <%= f.select :mhyouka_5, Plan.mhyouka_5s.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>

  <div class="form-group">
    <%= f.label :mhyoud_1, '目標次回評価日１' %>
    <%= f.date_select(:mhyoud_1,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>
  <div class="form-group">
    <%= f.label :mhyoud_2, '目標次回評価日２' %>
    <%= f.date_select(:mhyoud_2,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>
  <div class="form-group">
    <%= f.label :mhyoud_3, '目標次回評価日３' %>
    <%= f.date_select(:mhyoud_3,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>
  <div class="form-group">
    <%= f.label :mhyoud_4, '目標次回評価日４' %>
    <%= f.date_select(:mhyoud_4,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>
  <div class="form-group">
    <%= f.label :mhyoud_5, '目標次回評価日５' %>
    <%= f.date_select(:mhyoud_5,
    start_year: 2018,
    end_year:   (Time.now.year - 19),
    default:    Date.new(2018, 1,15)) %>
  </div>


  
  <button type="submit" class="btn btn-primary">投稿</button>
</form>

</div>
</div>
<% end %>

app/views/plans/edit.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>id: <%= @plan.id %> の編集ページ</h1>

<%= render 'form', plan: @plan %>

<%= link_to '一覧に戻る', plans_path %>
<%= link_to '削除', @plan, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/plans/index.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>

<div class="col-sm-10">
<% @patients.each do |patient| %>
<h2>
<ruby><rb><%= patient.p_name %><rt><%= patient.p_kana %></ruby>
<a href="../plans/<%= patient.id %>">show</a>
</h2>

   
<table class="table table-striped table-bordered table-condensed table-hover" style="table-layout:fixed;width:100%;">
  <tr>
   <th style="width:5%" class="text-center">患者</th>
   <th style="width:5%" class="text-center">id</th>
   <th style="width:40%" class="text-center">看護問題</th>
   <th style="width:15%" class="text-center">登録日</th>
   <th style="width:10%" class="text-center">評価</th>
   <th style="width:15%" class="text-center">次回評価日</th> 
  </tr>
<% patient.plans.each do |plan| %>
  <tr>
   <th style="width:5%" class="text-center"><%= plan.patient_id %></th>
   <td style="width:5%" class="text-center"><%= link_to plan.id, edit_plan_path(plan) %></td>
   <td style="word-wrap:break-word;" class="text-left"><%= plan.name %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.hyouka %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.jikai %></td>
  </tr>

  <% end %>
</table>

<% end %>
<%= link_to '新規投稿', new_plan_path %>
</div>

<div class="row col-sm-2">
<%= render 'layouts/sidebar' %>
</div>

app/views/plans/new.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>新規作成ページ</h1>

<%= render 'form', plan: @plan %>

<%= link_to '一覧に戻る', plans_path %>

app/views/plans/show.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
<div class="container">

<div class="row">
  <div class="col-md-2"><h2><ruby><rb><%= @patient.p_name %><rt><%= @patient.p_kana %></ruby></h2></div>

<% if @patient.gender == '男' %>
<div class="col-sm-1"><br><img border="0" src="../images/men1.png" width="60" height="60" alt="男性" title="男性"></div>
<% else %>
<div class="col-sm-1"><br><img border="0" src="../images/women1.png" width="60" height="60" alt="女性" title="女性"></div>
<% end %>

  <div class="col-md-4"><h3>生年月日：<%= @patient.birth_date.strftime('%Y年%m月%d日') %></h3></div>
  <div class="col-md-2"><h3>年齢：<%= @patient.age %>歳</h3></div>
<div class="col-sm-6"><h4>感染症：<%= @patient.infection %>&emsp;
アレルギー：<%= @patient.allergic %></h4></div>
</div>

<div class="row">
  <div class="col-md-3"><h4>入院日:<%= @patient.hos_date.strftime('%Y年%m月%d日 %H:%M') %></h4></div>
  <div class="col-md-2"><h4>部屋番号：<%= @patient.room_no %></h4></div>
  <div class="col-md-5"><h4>血液型：<%= @patient.bloodtype %>型&emsp;&emsp;身長：<%= @patient.height %>cm&emsp;体重：<%= @patient.weight %>kg
</h4></div>
</div>

</div></div>
</div>

<div class="col-sm-10">

<table class="table table-striped table-bordered table-condensed table-hover" style="table-layout:fixed;width:100%;">
  <tr class="info">
   <th style="width:5%" class="text-center">id</th>
   <th style="width:44%" class="text-center">内容</th>
   <th style="width:13%" class="text-center">登録日</th>
   <th style="width:13%" class="text-center">評価日</th>
   <th style="width:7%" class="text-center">評価</th>
   <th style="width:13%" class="text-center">次回評価日</th> 
  </tr>


<% @plans.each do |plan| %>

  <tr>
   <td class="text-center">#<%= link_to plan.plno, edit_plan_path(plan) %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= link_to plan.name, pdetail_path(plan) %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.hyokad.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.hyouka %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.jikai.strftime('%Y年%m月%d日') %></td>
  </tr>
  <tr>
   <th class="text-center">目標</th> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mokuhyo_1 %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyoud_1.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= truncate(plan.mhyouka_1, length:3) %></td> 
   <td style="word-wrap:break-word;" class="text-left"></td>
  </tr>
<% unless plan.mokuhyo_2 == '' %>
  <tr>
   <td class="text-center"></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mokuhyo_2 %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyoud_2.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyouka_2 %></td> 
   <td style="word-wrap:break-word;" class="text-left"></td>
  </tr>
<% end %>
<% unless plan.mokuhyo_3 == '' %>
  <tr>
   <td class="text-center"></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mokuhyo_3 %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyoud_3.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyouka_3 %></td> 
   <td style="word-wrap:break-word;" class="text-left"></td>
  </tr>
<% end %>
<% unless plan.mokuhyo_4 == '' %>
  <tr>
   <td class="text-center"></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mokuhyo_4 %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyoud_4.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyouka_4 %></td> 
   <td style="word-wrap:break-word;" class="text-left"></td>
  </tr>
<% end %>
<% unless plan.mokuhyo_5 == '' %>
  <tr>
   <td class="text-center"></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mokuhyo_5 %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.touroku.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyoud_5.strftime('%Y年%m月%d日') %></td> 
   <td style="word-wrap:break-word;" class="text-left"><%= plan.mhyouka_5 %></td> 
   <td style="word-wrap:break-word;" class="text-left"></td>
  </tr>
<% end %>


<% end %>
</table>

<%= link_to '一覧に戻る', plans_path %>

</div>

<div class="row col-sm-2">
<%= render 'layouts/sidebar' %>
</div>