config/routes.rb
class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end


Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :graphs, only: [:show,:index]

  resources :patients do
    collection do
      post :import
    end
  end

  resources :kansatus do
    collection do
      get :search
      post :import
    end
  end
  
  resources :tentous do
    collection do
      get :search
      post :import
    end
  end

  resources :saiketus do
    collection do
      get :search
      post :import
    end
  end
  resources :sensors

  resources :kekkas
  resources :plans

  resources :pdetails do
    collection do
      post :import
    end
  end

  resources :nreports

end

app/models/kansatu.rb
class Kansatu < ApplicationRecord
belongs_to :patient

validates :category,    length: { maximum: 50 }
validates :ob_name,    length: { maximum: 50 }
validates :n_1d,    length: { maximum: 50 }
validates :j_1d,    length: { maximum: 50 }
validates :s_2d,    length: { maximum: 50 }
validates :n_2d,    length: { maximum: 50 }
validates :j_2d,    length: { maximum: 50 }
validates :s_3d,    length: { maximum: 50 }
validates :n_3d,    length: { maximum: 50 }
validates :j_3d,    length: { maximum: 50 }
validates :s_4d,    length: { maximum: 50 }


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |kansatu|
        csv << kansatu.csv_column_values
      end
    end
  end

  def self.csv_column_names
    ["ID", "category", "観察名", "日勤1day", "準夜1day", "深夜2day", "日勤2day", "準夜2day", "深夜3day", "日勤3day", "準夜3day", "深夜4day", "患者id"]
  end

  def csv_column_values
    [id,category,ob_name,n_1d,j_1d,s_2d,n_2d,j_2d,s_3d,n_3d,j_3d,s_4d,patient_id]
  end


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      kansatu = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      kansatu.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      kansatu.save!
    end
  end 

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    when '.ods'  then Roo::OpenOffice.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["category","ob_name","n_1d","j_1d","s_2d","n_2d","j_2d","s_3d","n_3d","j_3d","s_4d","patient_id"]
  end


end

app/controllers/kansatus_controller.rb
class KansatusController < ApplicationController
  before_action :require_user_logged_in

  def index
    @kansatus = Kansatu.all
    @q        = Kansatu.search(params[:q])
    @kansatus = @q.result(distinct: true)
    respond_to do |format|
      format.html
      format.csv { send_data @kansatus.to_csv }
      format.xls { send_data @kansatus.to_csv(col_sep: "\t") }
    end

    def import
      # fileはtmpに自動で一時保存される
      Kansatu.import(params[:file])
      redirect_to kansatus_url, notice: "追加しました。"
    end
  end

  def show
    @kansatu = Kansatu.find(params[:id])
  end

  def new
    @kansatu = Kansatu.new
  end

  def create
    @kansatu = Kansatu.new(kansatu_params)

    if @kansatu.save
      flash[:success] = '正常に投稿されました'
      redirect_to @kansatu
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end

  def edit
    @kansatu = Kansatu.find(params[:id])
  end

  def update
    @kansatu = Kansatu.find(params[:id])

    if @kansatu.update(kansatu_params)
      flash[:success] = '正常に更新されました'
      redirect_to @kansatu
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @kansatu = Kansatu.find(params[:id])
    @kansatu.destroy

    flash[:success] = '正常に削除されました'
    redirect_to kansatus_url

  end

  private

  def kansatu_params
    params.require(:kansatu).permit(:category, :ob_name, :patient_id,
    :n_1d, :j_1d, :s_2d, :n_2d, :j_2d, :s_3d, :n_3d, :j_3d, :s_4d
    )
  end

end

app/views/kansatus/_form.html.erb
<%= form_for(kansatu) do |f| %>
  <div class="row">
    <div class="col-sm-6">
<form class="form-inline">

    <div class="form-group">
    <%= f.label :patient_id, '患者ＩＤ' %>
    <%= f.text_field :patient_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category, 'カテゴリー' %>
    <%= f.text_field :category, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :ob_name, '観察名' %>
    <%= f.text_field :ob_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :n_1d, '日勤1日目' %>
    <%= f.text_field :n_1d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :j_1d, '準夜1日目' %>
    <%= f.text_field :j_1d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :s_2d, '深夜2日目' %>
    <%= f.text_field :s_2d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :n_2d, '日勤2日目' %>
    <%= f.text_field :n_2d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :j_2d, '準夜2日目' %>
    <%= f.text_field :j_2d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :s_3d, '深夜3日目' %>
    <%= f.text_field :s_3d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :n_3d, '日勤3日目' %>
    <%= f.text_field :n_3d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :j_3d, '準夜3日目' %>
    <%= f.text_field :j_3d, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :s_4d, '深夜4日目' %>
    <%= f.text_field :s_4d, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-primary">投稿</button>
</form>

</div>
</div>
<% end %>

app/views/kansatus/_search_form.html.erb
<%= render layout: 'shared/search_box' do %>

<div class="row">
<div class="col-sm-6 col-sm-offset-3">
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">患者ＩＤ</label>
    <div class="col-sm-8">
      <%= f.text_field :patient_id_start, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">観察名</label>
    <div class="col-sm-8">
      <%= f.text_field :ob_name_start, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">category含まれる文字列</label>
    <div class="col-sm-8">
      <%= f.text_field :category_cont, class: 'form-control' %>
    </div>
  </div>
</div>

<div class="col-sm-12 row text-center">
  <%= link_to kansatus_path, class: 'btn btn-default btn-left' do %>クリア<% end %>
  <button class="btn btn-default btn-primary" type="submit"><i class="fa fa-search"></i> 検索</button>
</div>


</div>

<% end %>

app/views/kansatus/edit.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>id: <%= @kansatu.id %> の編集ページ</h1>

<%= render 'form', kansatu: @kansatu %>

<%= link_to '一覧に戻る', kansatus_path %>

app/views/kansatus/index.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<% content_for(:title) do %>
  観察項目検索
<% end %>

<%= search_form_for @q do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

<table class="table table-striped table-bordered table-condensed table-hover" style="table-layout:fixed;width:100%;">
  <tr>
   <th style="width:2%" class="text-right">患者id</th>
   <th style="width:6%" class="text-right">category</th>
   <th style="width:18%" class="text-right">観察名</th>
   <th style="width:8%" class="text-center">1day日勤</th> 
   <th style="width:8%" class="text-center">1day準夜</th> 
   <th style="width:8%" class="text-center">2day深夜</th>
   <th style="width:8%" class="text-center">2day日勤</th> 
   <th style="width:8%" class="text-center">2day準夜</th> 
   <th style="width:8%" class="text-center">3day深夜</th>
   <th style="width:8%" class="text-center">3day日勤</th> 
   <th style="width:8%" class="text-center">3day準夜</th> 
   <th style="width:8%" class="text-center">4day深夜</th>
   <th style="width:2%" class="text-right">id</th>
  </tr>
  <% @kansatus.each do |kansatu| %>
  <tr>
   <th style="width:2%" class="text-center"><%= kansatu.patient_id %></th>
   <th style="width:6%" class="text-center"><%= kansatu.category %></th>
   <th style="width:18%" class="text-right"><%= kansatu.ob_name %></th>
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.n_1d %></td>
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.j_1d %></td> 
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.s_2d %></td> 
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.n_2d %></td>
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.j_2d %></td> 
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.s_3d %></td> 
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.n_3d %></td>
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.j_3d %></td> 
   <td style="word-wrap:break-word;" class="text-center"><%= kansatu.s_4d %></td> 
   <td style="width:2%" class="text-center"><%= link_to kansatu.id, kansatu %></td>
  </tr>

  <% end %>
</table>

<br>
<div class="col-sm-12 row text-center">
<%= link_to 'CSV', kansatus_path(format: "csv"), class: 'btn btn-primary btn-left', id: "Download-btn" %>
<%= link_to 'Excel', kansatus_path(format: "xls"), class: 'btn btn-primary btn-left', id: "Download-btn" %>
</div>
<%= form_tag import_kansatus_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>

<%= link_to '新規投稿', new_kansatu_path %>

app/views/kansatus/new.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>新規作成ページ</h1>

<%= render 'form', kansatu: @kansatu %>

<%= link_to '一覧に戻る', kansatus_path %>

app/views/kansatus/search.html.erb
<% content_for(:title) do %>
  観察項目の検索結果
<% end %>

<%= search_form_for(@q, url: search_kansatus_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

<%= render layout: 'shared/search_result_box' do %>
  <table class="table table-list ">
  <thead>
    <tr>
   <th style="width:2%" class="text-right">患者id</th>
   <th style="width:6%" class="text-right">category</th>
   <th style="width:18%" class="text-right">名前</th>
   <th style="width:8%" class="text-center">1day日勤</th> 
   <th style="width:8%" class="text-center">1day準夜</th> 
   <th style="width:8%" class="text-center">2day深夜</th>
   <th style="width:8%" class="text-center">2day日勤</th> 
   <th style="width:8%" class="text-center">2day準夜</th> 
   <th style="width:8%" class="text-center">3day深夜</th>
   <th style="width:8%" class="text-center">3day日勤</th> 
   <th style="width:8%" class="text-center">3day準夜</th> 
   <th style="width:8%" class="text-center">4day深夜</th>
   <th style="width:2%" class="text-right">id</th>
    </tr>
  </thead>
  <% @kansatus.each do |kansatu| %>
  <tbody>
  <tr>
   <th style="width:2%" class="text-center"><%= kansatu.patient_id %></th>
   <th style="width:6%" class="text-center"><%= kansatu.category %></th>
   <th style="width:18%" class="text-right"><%= kansatu.ob_name %></th>
   <td style="width:8%" class="text-center"><%= kansatu.n_1d %></td>
   <td style="width:8%" class="text-center"><%= kansatu.j_1d %></td> 
   <td style="width:8%" class="text-center"><%= kansatu.s_2d %></td> 
   <td style="width:8%" class="text-center"><%= kansatu.n_2d %></td>
   <td style="width:8%" class="text-center"><%= kansatu.j_2d %></td> 
   <td style="width:8%" class="text-center"><%= kansatu.s_3d %></td> 
   <td style="width:8%" class="text-center"><%= kansatu.n_3d %></td>
   <td style="width:8%" class="text-center"><%= kansatu.j_3d %></td> 
   <td style="width:8%" class="text-center"><%= kansatu.s_4d %></td> 
   <td style="width:2%" class="text-center"><%= kansatu.id %></td>
  </tr>
  </tbody>
<% end %>
</table>
<% end %>

app/views/kansatus/show.html.erb
<div class="col-sm-12">
<div class="bs-docs-header" id="content">
</div>
</div>
<h1>id: <%= @kansatu.id %> の詳細ページ</h1>

    <p><%= @kansatu.category %></p>
    <p><%= @kansatu.ob_name %></p>
    <p><%= @kansatu.n_1d %></p>
    <p><%= @kansatu.j_1d %></p>
    <p><%= @kansatu.s_2d %></p>
    <p><%= @kansatu.n_2d %></p>
    <p><%= @kansatu.j_2d %></p>
    <p><%= @kansatu.s_3d %></p>
    <p><%= @kansatu.n_3d %></p>
    <p><%= @kansatu.j_3d %></p>
    <p><%= @kansatu.s_4d %></p>
    <p><%= @kansatu.patient_id %></p>
    
<%= link_to '一覧に戻る', kansatus_path %>
<%= link_to '編集', edit_kansatu_path(@kansatu) %>
<%= link_to '削除', @kansatu, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>